### ISSUE TITLE
Primary script unknown

### ISSUE THREAD

**Issue by edugsdf** [php-earth/docker-php#37]
![2019-08-12_183655_app1 local](https://user-images.githubusercontent.com/8173351/62900576-e172fc80-bd30-11e9-90cd-3f8b82fc6aee.png)

I use the duplicator to clone my site for local environment. When installing, it says it does not have write permission to the directory

docker-compose.yml:
```
version: '3.3'

services:
  app:
    image: phpearth/php:7.3-nginx
    volumes:
      - ./public_html:/var/www/html
    environment:
      - VIRTUAL_HOST=app1.local

networks:
  default:
    external:
      name: net-lemp
```
At the server console shows this:
`[error] 15#15: *15 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "172.18.0.5"
`
Can you help me?
